services:
  musicbot:
    build:
      context: .
    container_name: musicbot
    restart: unless-stopped
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    dns:
      - 1.1.1.1
      - 8.8.8.8
