services:
  kleebot:
    build:
      context: .
    image: kleebot
    container_name: kleebot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    dns:
      - 1.1.1.1
      - 8.8.8.8
